### ISSUE TITLE
vim-only fork

### ISSUE THREAD

**Issue by Shea690901** [omtcvxyz/solarized#1]
It would be nice to have a vim-only fork again...
That way it would be (again) quiet easy to use solarized as pathogen/vundle plugin...

**Comment by omtcvxyz** [comment]
Hi @Shea690901!
Makes sense, I will consider doing it once I'm back home.

**Comment by Shea690901** [comment]
Nothing urgent as long as there are no changes ;)

**Comment by omtcvxyz** [comment]
@Shea690901 sorry for such a huge delay. https://github.com/omtcvxyz/vim-colors-solarized up and running, fixed a recent issue with words marked by spell checker not being underlined anymore.

**Comment by Shea690901** [comment]
Nothing to be sorry for...
Neither of us earns any money from this...

Thanks anyway and setup changed accordingly ;)
